# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stuperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stuperformance.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_085a0d99c56a4c56b03b9439994f79ba }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b8a50a96416d48bfb7633e6c9cc67506 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stuperformance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_085a0d99c56a4c56b03b9439994f79ba }}/studenetperformance31jan:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stuperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_38d0c52fde0a4555a24b5c4141304794 }}
        images: 'stuperformance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_085a0d99c56a4c56b03b9439994f79ba }}/studenetperformance31jan:${{ github.sha }}'